# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ea2ae1ac0cb6a32c63eb47b719e6ccf3c814013e2cf437e7ce554f36dbe71b63ad1f205b2d7a483d98491deff0e3721ed6fc98f302a6ed21bec5de875334ea

test:
  secret_key_base: 856d46aa4eb80cce1c1fbb31d6522bbf0c570b62319446ab0a93baaa341a6e30d8565b189d4fd44d537571aab6f22f4c15b91e685b273f2b9dc7f8f8fd94ae6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
